#!/usr/bin/python

import sys
import urllib
import PyTango
from ffnet import loadnet



class PyDevice(PyTango.DeviceClass):
    cmd_list = {}
    attr_list = {'hrnn': [[PyTango.ArgType.DevFloat,
                           PyTango.AttrDataFormat.SCALAR,
                           PyTango.AttrWriteType.READ],
                           {'polling period': 2000}]}
    def __init__(self, name):
        PyTango.DeviceClass.__init__(self, name)
        self.set_type("TestDevice")


class PyHRNet(PyTango.Device_4Impl):
    def __init__(self, cl, name):
        self.net = loadnet('hrnet.net')
        PyTango.Device_4Impl.__init__(self, cl, name)
        self.info_stream('In PyHRNet.__init__')
        PyHRNet.init_device(self)

    def read_hrnn(self, the_att):
        dev = PyTango.DeviceProxy('C3/Aouda/AoudaOBDHJava')
        hr = dev['Heartrate'].value
        acc = dev['AccelerationBody'].value
        print 'hr, acc, output:', hr, acc,
        output = self.net([hr, acc])
        print output
        the_att.set_value(output[0])

    def is_hrnn_allowed(self, req_type):
        return self.get_state() == PyTango.DevState.ON

    def init_device(self):
        self.info_stream('In Python init_device method')
        self.set_state(PyTango.DevState.ON)


if __name__ == '__main__':
    util = PyTango.Util(sys.argv)
    util.add_class(PyDevice, PyHRNet)

    U = PyTango.Util.instance()
    U.server_init()
    U.server_run()
