#!/usr/bin/python

import sys
import time
import json
import redis
import PyTango


class UniqueMessageQueueWithDelay(object):
    def __init__(self, remote='hunveyor_test', local='local_test'):
        self.remote = remote
        self.local = local
        self.redis = redis.Redis(host='gwelican.eu', port=443)
        # clean queue
        self.redis.delete(local)

    def add(self, data, delay=0):
        temp = json.loads(data)
        temp["time"] = time.time()
        score = time.time() + delay
        self.redis.zadd(self.remote, json.dumps(temp), score)

    def pop(self, type):
        #min_score = 0
        #max_score = time.time()
        #result = self.redis.zrangebyscore(
            #self.local, min_score, max_score, start=0, num=1, withscores=False)
        for entry in self.redis.zrange(self.local, 0, -1):
            if type in entry:
                return entry
        return False

    def remove(self, data):
        return self.redis.zrem(self.local, data)


class PyDevice(PyTango.DeviceClass):
    cmd_list = {'start_simulation': [[PyTango.ArgType.DevVoid],
                                     [PyTango.ArgType.DevVoid]],
                'stop_simulation': [[PyTango.ArgType.DevVoid],
                                    [PyTango.ArgType.DevVoid]]}
    attr_list = {'temp': [[PyTango.ArgType.DevFloat,
                           PyTango.AttrDataFormat.SCALAR,
                           PyTango.AttrWriteType.READ],
                          {'polling period': 2000}],
                'humidity': [[PyTango.ArgType.DevFloat,
                              PyTango.AttrDataFormat.SCALAR,
                              PyTango.AttrWriteType.READ],
                             {'polling period': 2000}]}
    def __init__(self, name):
        PyTango.DeviceClass.__init__(self, name)
        self.set_type("TestDevice")


class PyHunveyorDevice(PyTango.Device_4Impl):
    def __init__(self, cl, name):
        PyTango.Device_4Impl.__init__(self, cl, name)
        self.info_stream('In PyHunveyorDevice.__init__')
        self.hunveyor = UniqueMessageQueueWithDelay()
        self.datafilename = 'hunveyor.data'
        self.simulation = False
        self.f = open(self.datafilename, 'a')
        PyHunveyorDevice.init_device(self)

    # XXX: simulation is currently broken
    # XXX: in the file there are now both temperature and humidity

    def start_simulation(self):
        if self.simulation:
            print 'Simulation already started...'
            return
        print 'Starting simulation...'
        self.simulation = True
        self.f.close()
        self.f = open(self.datafilename)

    def stop_simulation(self):
        if not self.simulation:
            print 'Simulation is not running...'
            return
        print 'Stopping simulation...'
        self.simulation = False
        self.f.close()
        self.f = open(self.datafilename, 'a')

    def write_data(self, data):
        #print 'writing', repr(data + '\n')
        self.f.write(data + '\n')
        self.f.flush()

    def read_temp(self, the_att):
        if self.simulation:
            self.simulation_read_temp(the_att)
        else:
            self.real_read_temp(the_att)

    def real_read_temp(self, the_att):
        self.info_stream("read_temp")
        data = self.hunveyor.pop('temperature')
        print 'read_temp: result is', data
        if data != False:
            result = json.loads(data)
            the_att.set_value(result['value'])
            self.write_data(data)
            self.hunveyor.remove(data)

        # request a new value
        data = {"command": "readtemp", "arguments": {"address": 0x92}}
        self.hunveyor.add(json.dumps(data))

    def simulation_read_temp(self, the_att):
        self.info_stream("read_temp")
        data = self.f.readline().strip() #XXX: must read temperature
        if not data:
            print 'Restarting simulation...'
            self.f.seek(0)
            data = self.f.readline().strip()
        print 'read_temp (sim): result is', data
        result = json.loads(data)
        the_att.set_value(result['value'])


    def read_humidity(self, the_att):
        if self.simulation:
            self.simulation_read_humidity(the_att)
        else:
            self.real_read_humidity(the_att)

    def real_read_humidity(self, the_att):
        self.info_stream("read_humidity")
        data = self.hunveyor.pop('humidity')
        print 'read_humidity: result is', data
        if data != False:
            result = json.loads(data)
            the_att.set_value(result['value'])
            self.write_data(data)
            self.hunveyor.remove(data)

        # request a new value
        data = {"command": "readhumidity", "arguments": {}}
        self.hunveyor.add(json.dumps(data))

    def simulation_read_humidity(self, the_att):
        self.info_stream("read_humidity")
        data = self.f.readline().strip() #XXX: must read humidity
        if not data:
            print 'Restarting simulation...'
            self.f.seek(0)
            data = self.f.readline().strip()
        print 'read_humidity (sim): result is', data
        result = json.loads(data)
        the_att.set_value(result['value'])

    def is_humidity_allowed(self, req_type):
        return self.get_state() == PyTango.DevState.ON

    def init_device(self):
        self.info_stream('In Python init_device method')
        self.set_state(PyTango.DevState.ON)

if __name__ == '__main__':
    util = PyTango.Util(sys.argv)
    util.add_class(PyDevice, PyHunveyorDevice)

    U = PyTango.Util.instance()
    U.server_init()
    U.server_run()
