/*----- PROTECTED REGION ID(AoudaOBDHClass.cpp) ENABLED START -----*/
static const char *RcsId      = "$Id:  $";
static const char *TagName    = "$Name:  $";
static const char *CvsPath    = "$Source:  $";
static const char *SvnPath    = "$HeadURL:  $";
static const char *HttpServer = "http://www.esrf.eu/computing/cs/tango/tango_doc/ds_doc/";
//=============================================================================
//
// file :        AoudaOBDHClass.cpp
//
// description : C++ source for the AoudaOBDHClass. A singleton
//               class derived from DeviceClass. It implements the
//               command list and all properties and methods required
//               by the «name» once per process.
//
// project :     ERAS_C3.
//
// $Author:  $
//
// $Revision:  $
// $Date:  $
//
// SVN only:
// $HeadURL:  $
//
// CVS only:
// $Source:  $
// $Log:  $
//
//=============================================================================
//                This file is generated by POGO
//        (Program Obviously used to Generate tango Object)
//=============================================================================


#include <AoudaOBDHClass.h>

/*----- PROTECTED REGION END -----*/

//-------------------------------------------------------------------
/**
 *	Create AoudaOBDHClass singleton and
 *	return it in a C function for Python usage
 */
//-------------------------------------------------------------------
extern "C" {
#ifdef _TG_WINDOWS_

__declspec(dllexport)

#endif

	Tango::DeviceClass *_create_AoudaOBDH_class(const char *name) {
		return AoudaOBDH_ns::AoudaOBDHClass::init(name);
	}
}


namespace AoudaOBDH_ns
{


//===================================================================
//	Initialize pointer for singleton pattern
//===================================================================
AoudaOBDHClass *AoudaOBDHClass::_instance = NULL;

//--------------------------------------------------------
/**
 * method : 		AoudaOBDHClass::AoudaOBDHClass(string &s)
 * description : 	constructor for the AoudaOBDHClass
 *
 * @param s	The class name
 */
//--------------------------------------------------------
AoudaOBDHClass::AoudaOBDHClass(string &s):DeviceClass(s)
{
	cout2 << "Entering AoudaOBDHClass constructor" << endl;
	set_default_property();
	get_class_property();
	write_class_property();

	/*----- PROTECTED REGION ID(AoudaOBDH::Class::constructor) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	AoudaOBDH::Class::constructor

	cout2 << "Leaving AoudaOBDHClass constructor" << endl;
}


//--------------------------------------------------------
/**
 * method : 		AoudaOBDHClass::~AoudaOBDHClass()
 * description : 	destructor for the AoudaOBDHClass
 */
//--------------------------------------------------------
AoudaOBDHClass::~AoudaOBDHClass()
{
	/*----- PROTECTED REGION ID(AoudaOBDH::Class::destructor) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	AoudaOBDH::Class::destructor

	_instance = NULL;
}


//--------------------------------------------------------
/**
 * method : 		AoudaOBDHClass::init
 * description : 	Create the object if not already done.
 *                  Otherwise, just return a pointer to the object
 *
 * @param	name	The class name
 */
//--------------------------------------------------------
AoudaOBDHClass *AoudaOBDHClass::init(const char *name)
{
	if (_instance == NULL)
	{
		try
		{
			string s(name);
			_instance = new AoudaOBDHClass(s);
		}
		catch (bad_alloc)
		{
			throw;
		}		
	}		
	return _instance;
}

//--------------------------------------------------------
/**
 * method : 		AoudaOBDHClass::instance
 * description : 	Check if object already created,
 *                  and return a pointer to the object
 */
//--------------------------------------------------------
AoudaOBDHClass *AoudaOBDHClass::instance()
{
	if (_instance == NULL)
	{
		cerr << "Class is not initialised !!" << endl;
		exit(-1);
	}
	return _instance;
}




//===================================================================
//	Command execution method calls
//===================================================================




//===================================================================
//	Properties management
//===================================================================

//--------------------------------------------------------
/**
 * method : 		AoudaOBDHClass::get_class_property
 * description : 	Get the class property for specified name.
 *
 * @param	name  The property name
 */
//--------------------------------------------------------
Tango::DbDatum AoudaOBDHClass::get_class_property(string &prop_name)
{
	for (unsigned int i=0 ; i<cl_prop.size() ; i++)
		if (cl_prop[i].name == prop_name)
			return cl_prop[i];
	//	if not found, returns  an empty DbDatum
	return Tango::DbDatum(prop_name);
}


//--------------------------------------------------------
/**
 *	Method      : AoudaOBDH::AoudaOBDHClass::get_default_device_property()()
 *	Description : Return the default value for device property.
 */
//--------------------------------------------------------
Tango::DbDatum AoudaOBDHClass::get_default_device_property(string &prop_name)
{
	for (unsigned int i=0 ; i<dev_def_prop.size() ; i++)
		if (dev_def_prop[i].name == prop_name)
			return dev_def_prop[i];
	//	if not found, return  an empty DbDatum
	return Tango::DbDatum(prop_name);
}


//--------------------------------------------------------
/**
 *	Method      : AoudaOBDH::AoudaOBDHClass::get_default_class_property()()
 *	Description : Return the default value for class property.
 */
//--------------------------------------------------------
Tango::DbDatum AoudaOBDHClass::get_default_class_property(string &prop_name)
{
	for (unsigned int i=0 ; i<cl_def_prop.size() ; i++)
		if (cl_def_prop[i].name == prop_name)
			return cl_def_prop[i];
	//	if not found, return  an empty DbDatum
	return Tango::DbDatum(prop_name);
}


//--------------------------------------------------------
/**
 *	Method      : AoudaOBDH::AoudaOBDHClass::get_class_property()
 *	Description : //	Add your own code to initialize
 */
//--------------------------------------------------------
void AoudaOBDHClass::get_class_property()
{
}


//--------------------------------------------------------
/**
 *	Method      : AoudaOBDH::AoudaOBDHClass::set_default_property()
 *	Description : Set default property (class and device) for wizard.
 *	              For each property, add to wizard property name and description.
 *	              If default value has been set, add it to wizard property and.
 *	              store it in a DbDatum.
 */
//--------------------------------------------------------
void AoudaOBDHClass::set_default_property()
{
	string	prop_name;
	string	prop_desc;
	string	prop_def;
	vector<string>	vect_data;
	
	//	Set Default Class Properties

	//	Set Default Device Properties
}


//--------------------------------------------------------
/**
 *	Method      : AoudaOBDH::AoudaOBDHClass::write_class_property()
 *	Description : Set class description fields as property in database
 */
//--------------------------------------------------------
void AoudaOBDHClass::write_class_property()
{
	//	First time, check if database used
	if (Tango::Util::_UseDb == false)
		return;

	Tango::DbData	data;
	string	classname = get_name();
	string	header;
	string::size_type	start, end;

	//	Put title
	Tango::DbDatum	title("ProjectTitle");
	string	str_title("ERAS_C3");
	title << str_title;
	data.push_back(title);

	//	Put Description
	Tango::DbDatum	description("Description");
	vector<string>	str_desc;
	str_desc.push_back("Aouda Telemetry Data acquisition");
	str_desc.push_back("");
	description << str_desc;
	data.push_back(description);
		
	//	put cvs or svn location
	string	filename("AoudaOBDH");
	filename += "Class.cpp";
	
	// check for cvs information
	string	src_path(CvsPath);
	start = src_path.find("/");
	if (start!=string::npos)
	{
		end   = src_path.find(filename);
		if (end>start)
		{
			string	strloc = src_path.substr(start, end-start);
			//	Check if specific repository
			start = strloc.find("/cvsroot/");
			if (start!=string::npos && start>0)
			{
				string	repository = strloc.substr(0, start);
				if (repository.find("/segfs/")!=string::npos)
					strloc = "ESRF:" + strloc.substr(start, strloc.length()-start);
			}
			Tango::DbDatum	cvs_loc("cvs_location");
			cvs_loc << strloc;
			data.push_back(cvs_loc);
		}
	}
	// check for svn information
	else
	{
		string	src_path(SvnPath);
		start = src_path.find("://");
		if (start!=string::npos)
		{
			end = src_path.find(filename);
			if (end>start)
			{
				header = "$HeadURL: ";
				start = header.length();
				string	strloc = src_path.substr(start, (end-start));
				
				Tango::DbDatum	svn_loc("svn_location");
				svn_loc << strloc;
				data.push_back(svn_loc);
			}
		}
	}

	//	Get CVS or SVN revision tag
	
	// CVS tag
	string	tagname(TagName);
	header = "$Name: ";
	start = header.length();
	string	endstr(" $");
	
	end   = tagname.find(endstr);
	if (end!=string::npos && end>start)
	{
		string	strtag = tagname.substr(start, end-start);
		Tango::DbDatum	cvs_tag("cvs_tag");
		cvs_tag << strtag;
		data.push_back(cvs_tag);
	}
	
	// SVN tag
	string	svnpath(SvnPath);
	header = "$HeadURL: ";
	start = header.length();
	
	end   = svnpath.find(endstr);
	if (end!=string::npos && end>start)
	{
		string	strloc = svnpath.substr(start, end-start);
		
		string tagstr ("/tags/");
		start = strloc.find(tagstr);
		if ( start!=string::npos )
		{
			start = start + tagstr.length();
			end   = strloc.find(filename);
			string	strtag = strloc.substr(start, end-start-1);
			
			Tango::DbDatum	svn_tag("svn_tag");
			svn_tag << strtag;
			data.push_back(svn_tag);
		}
	}

	//	Get URL location
	string	httpServ(HttpServer);
	if (httpServ.length()>0)
	{
		Tango::DbDatum	db_doc_url("doc_url");
		db_doc_url << httpServ;
		data.push_back(db_doc_url);
	}

	//  Put inheritance
	Tango::DbDatum	inher_datum("InheritedFrom");
	vector<string> inheritance;
	inheritance.push_back("Device_Impl");
	inher_datum << inheritance;
	data.push_back(inher_datum);

	//	Call database and and values
	get_db_class()->put_property(data);
}




//===================================================================
//	Factory methods
//===================================================================


//--------------------------------------------------------
/**
 * method : 		AoudaOBDHClass::device_factory
 * description : 	Create the device object(s)
 *                  and store them in the device list
 *
 * @param	*devlist_ptr	The device name list
 */
//--------------------------------------------------------
void AoudaOBDHClass::device_factory(const Tango::DevVarStringArray *devlist_ptr)
{

	/*----- PROTECTED REGION ID(AoudaOBDH::Class::device_factory_before) ENABLED START -----*/

	//	Add your own code

	/*----- PROTECTED REGION END -----*/	//	AoudaOBDH::Class::device_factory_before

	//	Create devices and add it into the device list
	for (unsigned long i=0 ; i<devlist_ptr->length() ; i++)
	{
		cout4 << "Device name : " << (*devlist_ptr)[i].in() << endl;
		device_list.push_back(new AoudaOBDH(this, (*devlist_ptr)[i]));							 
	}

	//	Manage dynamic attributes if any
	erase_dynamic_attributes(devlist_ptr, get_class_attr()->get_attr_list());

	//	Export devices to the outside world
	for (unsigned long i=1 ; i<=devlist_ptr->length() ; i++)
	{
		//	Add dynamic attributes if any
		AoudaOBDH *dev = static_cast<AoudaOBDH *>(device_list[device_list.size()-i]);
		dev->add_dynamic_attributes();

		//	Check before if database used.
		if ((Tango::Util::_UseDb == true) && (Tango::Util::_FileDb == false))
			export_device(dev);
		else
			export_device(dev, dev->get_name().c_str());
	}

	/*----- PROTECTED REGION ID(AoudaOBDH::Class::device_factory_after) ENABLED START -----*/

	//	Add your own code

	/*----- PROTECTED REGION END -----*/	//	AoudaOBDH::Class::device_factory_after

	
}


//--------------------------------------------------------
/**
 *	Method      : AoudaOBDH::AoudaOBDHClass::attribute_factory()
 *	Description : Create the attribute object(s)
 *	              and store them in the attribute list
 */
//--------------------------------------------------------
void AoudaOBDHClass::attribute_factory(vector<Tango::Attr *> &att_list)
{
	/*----- PROTECTED REGION ID(AoudaOBDH::Class::attribute_factory_before) ENABLED START -----*/

	//	Add your own code

	/*----- PROTECTED REGION END -----*/	//	AoudaOBDH::Class::attribute_factory_before


	//	Attribute : HelmetTemp
	HelmetTempAttrib	*helmettemp = new HelmetTempAttrib();
	Tango::UserDefaultAttrProp	helmettemp_prop;
	//	description	not set for	HelmetTemp
	//	label	not set for	HelmetTemp
	//	unit	not set for	HelmetTemp
	//	standard_unit	not set for	HelmetTemp
	//	display_unit	not set for	HelmetTemp
	//	format	not set for	HelmetTemp
	//	max_value	not set for	HelmetTemp
	//	min_value	not set for	HelmetTemp
	//	max_alarm	not set for	HelmetTemp
	//	min_alarm	not set for	HelmetTemp
	//	max_warning	not set for	HelmetTemp
	//	min_warning	not set for	HelmetTemp
	//	delta_t	not set for	HelmetTemp
	//	delta_val	not set for	HelmetTemp
	helmettemp->set_default_properties(helmettemp_prop);
	helmettemp->set_polling_period(5000);
	helmettemp->set_disp_level(Tango::OPERATOR);
	//	Not memorized

	//	HelmetTemp does not fire change event
	//	HelmetTemp does not fire archive event
	//	HelmetTemp does not fire data_ready event
	att_list.push_back(helmettemp);

	//	Attribute : HelmetHumidity
	HelmetHumidityAttrib	*helmethumidity = new HelmetHumidityAttrib();
	Tango::UserDefaultAttrProp	helmethumidity_prop;
	//	description	not set for	HelmetHumidity
	//	label	not set for	HelmetHumidity
	//	unit	not set for	HelmetHumidity
	//	standard_unit	not set for	HelmetHumidity
	//	display_unit	not set for	HelmetHumidity
	//	format	not set for	HelmetHumidity
	//	max_value	not set for	HelmetHumidity
	//	min_value	not set for	HelmetHumidity
	//	max_alarm	not set for	HelmetHumidity
	//	min_alarm	not set for	HelmetHumidity
	//	max_warning	not set for	HelmetHumidity
	//	min_warning	not set for	HelmetHumidity
	//	delta_t	not set for	HelmetHumidity
	//	delta_val	not set for	HelmetHumidity
	helmethumidity->set_default_properties(helmethumidity_prop);
	helmethumidity->set_polling_period(5000);
	helmethumidity->set_disp_level(Tango::OPERATOR);
	//	Not memorized

	//	HelmetHumidity does not fire change event
	//	HelmetHumidity does not fire archive event
	//	HelmetHumidity does not fire data_ready event
	att_list.push_back(helmethumidity);


	//	Create a list of static attributes
	create_static_attribute_list(get_class_attr()->get_attr_list());

	/*----- PROTECTED REGION ID(AoudaOBDH::Class::attribute_factory_after) ENABLED START -----*/

	//	Add your own code

	/*----- PROTECTED REGION END -----*/	//	AoudaOBDH::Class::attribute_factory_after

}


//--------------------------------------------------------
/**
 *	Method      : AoudaOBDH::AoudaOBDHClass::command_factory()
 *	Description : Create the command object(s)
 *	              and store them in the command list
 */
//--------------------------------------------------------
void AoudaOBDHClass::command_factory()
{
	/*----- PROTECTED REGION ID(AoudaOBDH::Class::command_factory_before) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	AoudaOBDH::Class::command_factory_before


	/*----- PROTECTED REGION ID(AoudaOBDH::Class::command_factory_after) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	AoudaOBDH::Class::command_factory_after

}




//===================================================================
//	Dynamic attributes related methods
//===================================================================


//--------------------------------------------------------
/**
 * method : 		AoudaOBDHClass::create_static_attribute_list
 * description : 	Create the a list of static attributes
 *
 * @param	att_list	the ceated attribute list 
 */
//--------------------------------------------------------
void AoudaOBDHClass::create_static_attribute_list(vector<Tango::Attr *> &att_list)
{
	for (unsigned long i=0 ; i<att_list.size() ; i++)
	{
		string att_name(att_list[i]->get_name());
		transform(att_name.begin(), att_name.end(), att_name.begin(), ::tolower);
		defaultAttList.push_back(att_name);
	}

	cout2 << defaultAttList.size() << " attributes in default list" << endl;


	/*----- PROTECTED REGION ID(AoudaOBDH::Class::create_static_att_list) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	AoudaOBDH::Class::create_static_att_list

}


//--------------------------------------------------------
/**
 * method : 		AoudaOBDHClass::erase_dynamic_attributes
 * description : 	delete the dynamic attributes if any.
 *
 * @param	devlist_ptr	the device list pointer
 * @param	list of all attributes
 */
//--------------------------------------------------------
void AoudaOBDHClass::erase_dynamic_attributes(const Tango::DevVarStringArray *devlist_ptr, vector<Tango::Attr *> &att_list)
{
	Tango::Util *tg = Tango::Util::instance();

	for (unsigned long i=0 ; i<devlist_ptr->length() ; i++)
	{	
		Tango::DeviceImpl *dev_impl = tg->get_device_by_name(((string)(*devlist_ptr)[i]).c_str());
		AoudaOBDH *dev = static_cast<AoudaOBDH *> (dev_impl);
		
		vector<Tango::Attribute *> &dev_att_list = dev->get_device_attr()->get_attribute_list();
		vector<Tango::Attribute *>::iterator ite_att;
		for (ite_att=dev_att_list.begin() ; ite_att != dev_att_list.end() ; ++ite_att)
		{
			string att_name((*ite_att)->get_name_lower());
			if ((att_name == "state") || (att_name == "status"))
				continue;
			vector<string>::iterator ite_str = find(defaultAttList.begin(), defaultAttList.end(), att_name);
			if (ite_str == defaultAttList.end())
			{
				cout2 << att_name << " is a UNWANTED dynamic attribute for device " << (*devlist_ptr)[i] << endl;
				Tango::Attribute &att = dev->get_device_attr()->get_attr_by_name(att_name.c_str());
				dev->remove_attribute(att_list[att.get_attr_idx()],true);
				--ite_att;
			}
		}
	}
	/*----- PROTECTED REGION ID(AoudaOBDH::Class::erase_dynamic_attributes) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	AoudaOBDH::Class::erase_dynamic_attributes

}



	/*----- PROTECTED REGION ID(AoudaOBDH::Class::Additional Methods) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	AoudaOBDH::Class::Additional Methods

} //	namespace
