/*----- PROTECTED REGION ID(AoudaOBDHStateMachine.cpp) ENABLED START -----*/
static const char *RcsId = "$Id:  $";
//=============================================================================
//
// file :        AoudaOBDHStateMachine.cpp
//
// description : C++ source for the «name» and its alowed
//               methods for commands and attributes
//
// project :     ERAS_C3.
//
// $Author:  $
//
// $Revision:  $
// $Date:  $
//
// SVN only:
// $HeadURL:  $
//
// CVS only:
// $Source:  $
// $Log:  $
//
//=============================================================================
//                This file is generated by POGO
//        (Program Obviously used to Generate tango Object)
//=============================================================================



#include <AoudaOBDH.h>
#include <AoudaOBDHClass.h>

/*----- PROTECTED REGION END -----*/


/*
 * AoudaOBDH states description:
 *
 */

namespace AoudaOBDH_ns
{

//=================================================
//		Attributes Allowed Methods
//=================================================

//--------------------------------------------------------
/**
 *	Method      : AoudaOBDH::is_HelmetTempState_allowed()
 *	Description : Execution allowed for HelmetTemp attribute.
 */
//--------------------------------------------------------

bool AoudaOBDH::is_HelmetTemp_allowed(Tango::AttReqType type)
{
		//	Not any excluded states for HelmetTemp attribute in READ access.
	
	/*----- PROTECTED REGION ID(AoudaOBDH::read_HelmetTempStateAllowed_READ) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	AoudaOBDH::read_HelmetTempStateAllowed_READ

	return true;
}

//--------------------------------------------------------
/**
 *	Method      : AoudaOBDH::is_HelmetHumidityState_allowed()
 *	Description : Execution allowed for HelmetHumidity attribute.
 */
//--------------------------------------------------------

bool AoudaOBDH::is_HelmetHumidity_allowed(Tango::AttReqType type)
{
		//	Not any excluded states for HelmetHumidity attribute in READ access.
	
	/*----- PROTECTED REGION ID(AoudaOBDH::read_HelmetHumidityStateAllowed_READ) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	AoudaOBDH::read_HelmetHumidityStateAllowed_READ

	return true;
}


	/*----- PROTECTED REGION ID(AoudaOBDH::are_dynamic_attributes_allowed) ENABLED START -----*/

	//	Add your code to check if dynamic attributes are alowed

	/*----- PROTECTED REGION END -----*/	//	AoudaOBDH::are_dynamic_attributes_allowed


//=================================================
//		Commands Allowed Methods
//=================================================



	/*----- PROTECTED REGION ID(AoudaOBDH::are_dynamic_commands_allowed) ENABLED START -----*/

	//	Add your code to check if dynamic commands are alowed

	/*----- PROTECTED REGION END -----*/	//	AoudaOBDH::are_dynamic_commands_allowed

}	// namespace AoudaOBDH_ns
